using System;
using System.Collections.Generic;
using System.Threading;
using Cysharp.Threading.Tasks;
using EndlessGuard.Unit.Runtime;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

// 논리적 SceneType과 실제 Unity 씬 이름 간의 직렬화 매핑 엔트리 구조체
[Serializable]
public struct SceneMappingEntry
{
    [Tooltip("논리적 씬 식별자")]
    public SceneType sceneType;

    [Tooltip("실제 Unity Build Settings에 등록된 씬 이름")]
    public string sceneName;
}

// 씬 전환, 런타임 페이드 캔버스 자동 생성, 자동 세이브 및 비동기 로딩 싱글톤 매니저
public class SceneLoader : SingletonBase<SceneLoader>
{
    #region 직렬화 변수

    [Header("--- 씬 이름 매핑 설정 ---")]
    [Tooltip("논리적 SceneType별 실제 Unity 씬 이름 매핑 목록 (인스펙터에서 자유롭게 수정 가능)")]
    [SerializeField] private List<SceneMappingEntry> sceneMappings = new List<SceneMappingEntry>();

    [Header("--- 페이드 연출 설정 ---")]
    [Tooltip("화면 암전(Fade Out) 소요 시간(초)")]
    [SerializeField] private float fadeOutDuration = 0.35f;

    [Tooltip("화면 밝아짐(Fade In) 소요 시간(초)")]
    [SerializeField] private float fadeInDuration = 0.35f;

    [Tooltip("씬 전환 완료 후 최소 대기 시간(초)")]
    [SerializeField] private float minLoadingWaitDuration = 0.2f;

    #endregion

    #region 내부 런타임 필드

    private readonly Dictionary<SceneType, string> _sceneNameMap = new Dictionary<SceneType, string>();
    private CanvasGroup _fadeCanvasGroup;
    private bool _isLoading = false;

    #endregion

    #region 프로퍼티

    public SceneType CurrentSceneType { get; private set; } = SceneType.Lobby;
    public bool IsLoading => _isLoading;
    public float FadeOutDuration => fadeOutDuration;
    public float FadeInDuration => fadeInDuration;

    #endregion

    #region 라이프 사이클 및 캔버스 자동 생성

    // 싱글톤 초기화, 씬 매핑 맵 구성 및 페이드 UI 자동 생성
    protected override void Awake()
    {
        base.Awake();

        InitializeDefaultSceneMappings();
        EnsureFadeOverlayUI();
    }

    // 씬 매핑 딕셔너리 초기화
    private void InitializeDefaultSceneMappings()
    {
        _sceneNameMap.Clear();

        _sceneNameMap[SceneType.Lobby] = "BackSystem2";
        _sceneNameMap[SceneType.GamePlay] = "Main_Test1";
        _sceneNameMap[SceneType.Raid] = "RaidScene";

        if (sceneMappings != null)
        {
            for (int i = 0; i < sceneMappings.Count; i++)
            {
                SceneMappingEntry entry = sceneMappings[i];
                if (!string.IsNullOrEmpty(entry.sceneName))
                {
                    _sceneNameMap[entry.sceneType] = entry.sceneName;
                }
            }
        }

        if (sceneMappings == null || sceneMappings.Count == 0)
        {
            sceneMappings = new List<SceneMappingEntry>();
            foreach (var pair in _sceneNameMap)
            {
                sceneMappings.Add(new SceneMappingEntry
                {
                    sceneType = pair.Key,
                    sceneName = pair.Value
                });
            }
        }
    }

    // 에디터 인스펙터 값 변경 시 런타임 맵 동기화
    private void OnValidate()
    {
        if (sceneMappings == null) return;

        for (int i = 0; i < sceneMappings.Count; i++)
        {
            SceneMappingEntry entry = sceneMappings[i];
            if (!string.IsNullOrEmpty(entry.sceneName))
            {
                _sceneNameMap[entry.sceneType] = entry.sceneName;
            }
        }
    }

    // 화면 최상위 페이드 캔버스 런타임 자동 생성
    private void EnsureFadeOverlayUI()
    {
        if (_fadeCanvasGroup != null) return;

        GameObject overlayObj = new GameObject("[AutoGenerated_FadeCanvas]");
        overlayObj.transform.SetParent(transform, false);

        Canvas canvas = overlayObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 9999;

        CanvasScaler scaler = overlayObj.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);

        overlayObj.AddComponent<GraphicRaycaster>();

        _fadeCanvasGroup = overlayObj.AddComponent<CanvasGroup>();
        _fadeCanvasGroup.alpha = 0.0f;
        _fadeCanvasGroup.blocksRaycasts = false;
        _fadeCanvasGroup.interactable = false;

        GameObject bgObj = new GameObject("BlackFadeImage");
        bgObj.transform.SetParent(overlayObj.transform, false);

        Image bgImage = bgObj.AddComponent<Image>();
        bgImage.color = Color.black;

        RectTransform rectTransform = bgObj.GetComponent<RectTransform>();
        rectTransform.anchorMin = Vector2.zero;
        rectTransform.anchorMax = Vector2.one;
        rectTransform.sizeDelta = Vector2.zero;
    }

    #endregion

    #region 씬 전환 공개 API

    // SceneType 기반 씬 전환 요청
    public void LoadScene(SceneType targetScene, bool useFade = true)
    {
        LoadSceneAsync(targetScene, useFade).Forget();
    }

    // SceneType 기반 비동기 씬 전환 연산
    public async UniTask LoadSceneAsync(SceneType targetScene, bool useFade = true)
    {
        string sceneName = GetSceneName(targetScene);
        await LoadSceneInternalAsync(targetScene, sceneName, useFade);
    }

    // 씬 이름 직접 지정 기반 씬 전환 요청
    public void LoadSceneByName(string sceneName, bool useFade = true)
    {
        LoadSceneByNameAsync(sceneName, useFade).Forget();
    }

    // 씬 이름 직접 지정 기반 비동기 씬 전환 연산
    public async UniTask LoadSceneByNameAsync(string sceneName, bool useFade = true)
    {
        SceneType matchedType = FindSceneTypeByName(sceneName);
        await LoadSceneInternalAsync(matchedType, sceneName, useFade);
    }

    // SceneType에 매핑된 실제 씬 이름 반환
    public string GetSceneName(SceneType sceneType)
    {
        if (_sceneNameMap.TryGetValue(sceneType, out string name) && !string.IsNullOrEmpty(name))
        {
            return name;
        }

        return sceneType switch
        {
            SceneType.Lobby => "BackSystem2",
            SceneType.GamePlay => "Main_Test1",
            SceneType.Raid => "RaidScene",
            _ => "BackSystem2"
        };
    }

    // 특정 SceneType의 실제 씬 이름 런타임 갱신
    public void SetSceneMapping(SceneType sceneType, string newSceneName)
    {
        if (string.IsNullOrEmpty(newSceneName)) return;

        _sceneNameMap[sceneType] = newSceneName;

        for (int i = 0; i < sceneMappings.Count; i++)
        {
            if (sceneMappings[i].sceneType == sceneType)
            {
                sceneMappings[i] = new SceneMappingEntry
                {
                    sceneType = sceneType,
                    sceneName = newSceneName
                };
                return;
            }
        }

        sceneMappings.Add(new SceneMappingEntry
        {
            sceneType = sceneType,
            sceneName = newSceneName
        });
    }

    #endregion

    #region 내부 비동기 로딩 및 페이드 처리

    // 내부 비동기 씬 로딩, 자동 세이브 및 상태 동기화 루프
    private async UniTask LoadSceneInternalAsync(SceneType targetScene, string sceneName, bool useFade)
    {
        if (_isLoading)
        {
            Debug.LogWarning($"[SceneLoader] 이미 씬 전환 중입니다. (요청: {sceneName})");
            return;
        }

        _isLoading = true;
        CancellationToken token = this.GetCancellationTokenOnDestroy();

        try
        {
            Debug.Log($"[SceneLoader] 씬 전환 시작: {CurrentSceneType} -> {targetScene} ('{sceneName}')");

            EventBus.Publish(new RequestSaveGameEvent(force: true));

            Time.timeScale = 1.0f;
            if (SpawnedEnemyManager.Instance != null)
            {
                SpawnedEnemyManager.Instance.ClearAll();
            }

            EventBus.Publish(new SceneLoadStartEvent(targetScene, sceneName));

            if (useFade && _fadeCanvasGroup != null)
            {
                _fadeCanvasGroup.blocksRaycasts = true;
                await FadeAsync(1.0f, fadeOutDuration, token);
            }

            AsyncOperation asyncOp = SceneManager.LoadSceneAsync(sceneName);
            if (asyncOp == null)
            {
                Debug.LogError($"[SceneLoader] 씬 로드 실패: '{sceneName}'이 Build Settings에 등록되어 있는지 확인하세요.");
                if (useFade && _fadeCanvasGroup != null)
                {
                    await FadeAsync(0.0f, fadeInDuration, token);
                    _fadeCanvasGroup.blocksRaycasts = false;
                }
                return;
            }

            asyncOp.allowSceneActivation = true;

            while (!asyncOp.isDone)
            {
                float progress = Mathf.Clamp01(asyncOp.progress / 0.9f);
                EventBus.Publish(new SceneLoadProgressEvent(targetScene, progress));
                await UniTask.Yield(PlayerLoopTiming.Update, token);
            }

            if (minLoadingWaitDuration > 0f)
            {
                await UniTask.Delay(TimeSpan.FromSeconds(minLoadingWaitDuration), cancellationToken: token);
            }

            CurrentSceneType = targetScene;

            if (SaveManager.Instance != null)
            {
                SaveManager.Instance.LoadGameData();
            }

            if (GameManager.Instance != null)
            {
                GameState targetState = (targetScene == SceneType.GamePlay)
                    ? GameState.InGame
                    : (targetScene == SceneType.Lobby ? GameState.Lobby : GameState.Title);
                GameManager.Instance.ChangeState(targetState);
            }

            EventBus.Publish(new SceneLoadCompletedEvent(targetScene, sceneName));

            if (useFade && _fadeCanvasGroup != null)
            {
                await FadeAsync(0.0f, fadeInDuration, token);
                _fadeCanvasGroup.blocksRaycasts = false;
            }

            Debug.Log($"[SceneLoader] 씬 전환 완료: '{sceneName}' (상태: {targetScene})");
        }
        catch (OperationCanceledException)
        {
            Debug.Log("[SceneLoader] 씬 로딩 작업이 취소되었습니다.");
        }
        catch (Exception ex)
        {
            Debug.LogError($"[SceneLoader] 씬 로딩 중 예외 발생: {ex.Message}");
        }
        finally
        {
            _isLoading = false;
            if (_fadeCanvasGroup != null)
            {
                _fadeCanvasGroup.blocksRaycasts = false;
            }
        }
    }

    // CanvasGroup 페이드 알파 보간 연산
    private async UniTask FadeAsync(float targetAlpha, float duration, CancellationToken token)
    {
        if (_fadeCanvasGroup == null) return;
        if (duration <= 0f)
        {
            _fadeCanvasGroup.alpha = targetAlpha;
            return;
        }

        float startAlpha = _fadeCanvasGroup.alpha;
        float elapsed = 0f;

        while (elapsed < duration)
        {
            token.ThrowIfCancellationRequested();
            elapsed += Time.unscaledDeltaTime;
            _fadeCanvasGroup.alpha = Mathf.Lerp(startAlpha, targetAlpha, elapsed / duration);
            await UniTask.Yield(PlayerLoopTiming.Update, token);
        }

        _fadeCanvasGroup.alpha = targetAlpha;
    }

    // 씬 이름 기반 SceneType 역탐색
    private SceneType FindSceneTypeByName(string sceneName)
    {
        if (string.IsNullOrEmpty(sceneName)) return SceneType.Lobby;

        foreach (var pair in _sceneNameMap)
        {
            if (string.Equals(pair.Value, sceneName, StringComparison.OrdinalIgnoreCase))
            {
                return pair.Key;
            }
        }

        return SceneType.GamePlay;
    }

    #endregion
}
